### ISSUE TITLE
_options.AddPolicy is not thread-safe

### ISSUE THREAD

**Issue by rabbal** [JonPSmith/PermissionAccessControl#3]
Hi

Because AddPolicy method of AuthorizationOptions is not thread-safe, adding created policies to [_options](https://github.com/JonPSmith/PermissionAccessControl/blob/master/RolesToPermission/AuthorizationPolicyProvider.cs#L34) at run-time maybe cause error.
As a workaround, we can use [LazyConcurrentDictionary](https://github.com/rabbal/DNTFrameworkCore/blob/master/src/DNTFrameworkCore/Helpers/LazyConcurrentDictionary.cs) that I use it in [DNTFrameworkCore](https://github.com/rabbal/DNTFrameworkCore)

```C# 
public class AuthorizationPolicyProvider : DefaultAuthorizationPolicyProvider
{
    private readonly LazyConcurrentDictionary<string, AuthorizationPolicy> _policies =
        new LazyConcurrentDictionary<string, AuthorizationPolicy>(StringComparer.OrdinalIgnoreCase);

    public AuthorizationPolicyProvider(IOptions<AuthorizationOptions> options)
        : base(options)
    {
    }

    public override async Task<AuthorizationPolicy> GetPolicyAsync(string policyName)
    {
        if (!policyName.StartsWith(PermissionConstant.PolicyPrefix, StringComparison.OrdinalIgnoreCase))
        {
            return await base.GetPolicyAsync(policyName);
        }

        var policy = _policies.GetOrAdd(policyName, name =>
        {
            var permissions = policyName.ExtractPermissionsFromPolicyName();

            return new AuthorizationPolicyBuilder()
                .AddRequirements(new PermissionAuthorizationRequirement(permissions))
                .Build();
        });

        return policy;
    }
}
```

**Comment by JonPSmith** [comment]
Hi @rabbal,

Thank you so much for pointing that out - didn't know that.  I have a couple of questions:
1. Why do you use a `LazyConcurrentDictionary` rather than a  `ConcurrentDictionary`. I would have thought that the dictionary would be used most of the time (unless you have a lot of your own policies registered via DI).
2. You have added a check for a check on the start of the policy name. I assume you add a prefix to all the Enums, or alter the `[HasPermission]` attribute. I assume this is just to improve performance - correct?

**Comment by rabbal** [comment]
1- [GetOrAdd method of ConcurrentDictionary is not thread-safe](https://github.com/aspnet/AspNetCore/blob/c565386a3ed135560bc2e9017aa54a950b4e35dd/src/Mvc/Mvc.Core/src/Filters/MiddlewareFilterBuilder.cs#L17)
2-  You right, [also I want to proccess just permission policies](https://github.com/rabbal/DNTFrameworkCore/blob/master/src/DNTFrameworkCore.Web/Authorization/PermissionAuthorizeAttribute.cs#L16). I don't use enum for permission; instead I use [const strings](https://github.com/rabbal/DNTFrameworkCore/blob/master/test/DNTFrameworkCore.TestAPI/Authorization/PermissionNames.cs#L5) with short length. 
```C#
    public static class PermissionNames
    {
        public const string Blogs_View = "10"; // For minimize token/cookie size
        public const string Blogs_Create = nameof(Blogs_Create);
        public const string Blogs_Edit = nameof(Blogs_Edit);
        public const string Blogs_Delete = nameof(Blogs_Delete);
    }
```
Thank you @JonPSmith for your idea about minimize cookie size by using series of integers to store as permissions

**Comment by JonPSmith** [comment]
Hi @rabbal,

Wow, its hard to know what is thread safe. Its really not obvious that the GetOrAdd method of ConcurrentDictionary is not thread-safe I have used `ConcurrentDictionary` thinking that the Concurrent part of the name meant it was thread safe. Thanks for pointing that out and providing a a solution.

I'm busy at the moment so I will leave this open until I fix it.

**Comment by JonPSmith** [comment]
HI @rabbal ,

Thanks for closing this issue. You see I fixed it but I forgot to close the issue.
